### ISSUE TITLE
downloadModule fails when module is a git submodule

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#105]
`downloadModule("LandMine")` and `downloadModule("wolfAlps")` both fail because the http request in `checkModule()` doesn't get the module files for these git submodules.

E.g., line 115 of module-repository.R will return only `"modules/moduleName"` without listed files nor subdirectories.

**Comment by eliotmcintire** [comment]
Closing. Low priority. Labelled "NotDone"

**Comment by eliotmcintire** [comment]
Actually, this was done. Removing label. In commit 7a0f079c20e205cae8a4f97fb62956bff64076f2 and others
