### ISSUE TITLE
Feature request: get all objects from a `simList` to pass to another `simInit` call

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#115]
I'm currently running prep `simInitAndSpades` calls (with `time$start <- time$end <- 0`, e.g.) that produce a `simList` (let's call it `preSimList`) with objects that I need to pass to a "final" `simInitAndSpades` call, which  will run my actual simulations.

Upon doing this, I realised it's quite annoying to manually extract objects from the `preSimList` into an `objectsList` that is passed to `simInit...(..., objects = objectsList, ...)`, especially when there are many many of them.

So I was wondering if there's a way to add a feature to SpaDES.core to do this. For now, this is what I'm doing:
```
preSimList<- simInitAndSpades(...)

objectsList <- lapply(ls(preSimList@.xData), FUN = function(x) {
  get(x, envir = preSimList@.xData)
})
names(objectsList) <- ls(preSimList@.xData)

finalSimList <- simInitAndSpades(..., objects = objectsList, ...)
```

**Comment by eliotmcintire** [comment]
I think this may do what you need. Note use of `objs` which extracts all the non-hidden objects in the `simList`
```
preSimList<- simInitAndSpades(objects = list(a = 1))
finalSimList <- simInitAndSpades(objects = objs(preSimList))
```
