### ISSUE TITLE
Add generic function to create `studyArea` and/or `rasterToMatch`

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#116]
`studyArea `and `rasterToMatch` are now the standard objects used to define the simulation landscape and so it may be useful to standardize how they can be created by default. This may be extended to their counterparts `studyAreaLarge` and `rasterToMatchLarge`
The current flow implemented across LandR modules could serve as the basis for this function, which would then be included in the `newModule` template's `.inputObjects`  section.

This is the current flow in the modules (SA stands for `studyArea`, RTM for `rasterToMatch`):

1. Check if SA/SALarge exist 
2. If they don't, make a dummy one in Alberta, Canada
3. Check that SALarge _contains_ SA
4. Check if RTM/RTMLarge exist
5. If they don't, check if rawBiomassMap exists
6. If it does, check that it's properties (only extent/crs can be compared) match SA/SALarge, depending on which of them needs to be created. If properties do not match, do the alternative no. do 7.
7. If it doesn't, get a default one and mask/crop it to SALarge or SA (depending on module needs) - put it in `simList` if needed by the module, otherwise keep it in a temporary object
8. Make RTMLarge (if rawBiomassMap was made to match SALarge) by assigning 1s to all !is.na(rawBiomassMap[]), then save it
8. Make RTM from RTMLarge, using SA 
OR 
Make RTM (if rawBiomassMap was made to match SA) it by assigning 1s to all !is.na(rawBiomassMap[]), then save it

**Comment by eliotmcintire** [comment]
This is not a complete decision tree. It needs to be fleshed out more. @ianmseddy Is this affecting you and is it a high enough priority for you to tackle it?

Closing this. Low priority. Labelled "NotDone".
