### ISSUE TITLE
check for use of library()/require() and setwd() calls in module R/filename.R

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#117]
I've seen multiple users putting code in the `R/` subdirectory of their module that will load packages or change paths.
This needs to be aggressively discouraged/caught because it causes hard-to-track errors during `simInit()` (these files are `source`d before `.inputObjects` is run).

1. Never call e.g., `library()` from within a module. Use `reqdPkgs` in module metadata to deal with package loading.
2. Do not change/set paths.

We should scan for use of `require()`, `library()`, `setwd()`, and other 'unsafe' calls that would accidentally bypass how modules/sims are run, and report an error to the user.

**Comment by achubaty** [comment]
Harder to check for, but also a common error: loading data from disk directly in these `.R` files using hardcoded paths.

**Comment by achubaty** [comment]
This guidance should also be added to documentation/vignettes.

**Comment by eliotmcintire** [comment]
Closing -- labelling "Not Done"
