### ISSUE TITLE
replace updateList() with Require::modifyList2()

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#121]

**Comment by eliotmcintire** [comment]
Now there is also a "multiple list" version in `Require::modifyList2`

**Comment by eliotmcintire** [comment]
Done with 3604589339e75505b7bd3af1a5625cb6ae3f30bf

**Comment by eliotmcintire** [comment]
The fact that `updateList` dealt with `NULL` values and `modifyList` doesn't, was a deal breaker for in situ swap. There is a new function in `Require::modifyList2` which wraps `utils::modifyList`, _and_ allows `NULL` list entries. To not have to deal with this, I have left `updateList` in place, but it uses `modifyList` internally (with catches for NULL). When `Require 0.9.0` is on CRAN, then we can swap out for `modifyList2` internally.

**Comment by achubaty** [comment]
was this subsequently updated ?

**Comment by eliotmcintire** [comment]
Just pushed b60e6580c0eeb358cc477a47499c75a5b93871c7 which should complete this
