### ISSUE TITLE
Allow modules as R packages

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/SpaDES.core#135]
I believe we can probably treat modules as packages and all functions, and imports just get put in the right place, without needing to put them in the simList. All I did was create a DESCRIPTION file and did a devtools::document() and a devtools::install() and all the functions were put into a package, namespacing all correct (as if it were a package), and it gets put in the search() path, like any other library, gets all the documentation correct (using roxygen2). That means that A LOT of work that I (and others) spent getting all the environments set up up, and namespacing setup etc. may have been unnecessary.

But my hunch is that by doing 4 things:

1. Make a DESCRIPTION file -- can be deduced from metadata
2. Put defineModule in inst folder, along with .Rmd (or in vignettes folder)
3. move main module file to R folder
4. adjust inner workings of SpaDES.core to follow this

What we gain 
1. documentation in place (we don't have this at all, except inside the source code) -- e.g., `?coverOptimFn` will give the documentation for that function, plus access to all the `pkgdown` tools for web page creation
2. we show that a module is essentially an R package... for advanced people who are rightfully skeptical of the module as we have done this is good (this is currently obscured)
3. correct importing of other package functions (we have this wrong right now)
4. We could put modules on CRAN

At least the first 3 of these benefits are likely really important.

**Comment by achubaty** [comment]
We have definitely had this discussion earlier on. Is the additional overhead of making into a package (and one that passes R CMD check) may be too high of a bar? I agree there are lots of benefits to this, as you mention above. Additionally, we gain the ease of getting unit tests and can use CI to automatically run tests as we make changes.

**Comment by eliotmcintire** [comment]
I belive that we can have modules be either as they are now or as packages, so we don't have to force anything on a user. The DESCRIPTION file, for example, can be generated automatically from the metadata. If a user wants their module to be a package, then they can choose to run R CMD check on it or not.

Thinking through the steps, I think one more user-visible difference is that a user would have to import SpaDES.core functions, whereas now they don't have to.

**Comment by achubaty** [comment]
@eliotmcintire I believe this was this was implemented, no?

**Comment by eliotmcintire** [comment]
It works, but there are no instructions/documentation. So no.
