### ISSUE TITLE
saveSimList(..., fileBackend = 1) is not saving rasters?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#139]
I tried saving the output `simList `from `SpaDES.experiment::experminent2` with `saveSimList(..., fileBackend = 1)` .

The documentation of suggests that if `fileBackend = 1` and `filebackedDir = NULL` , then "[raster] files will be copied to the directory: file.path(dirname(filename), "rasters").". However no such directory is created and the rasters do not seem to be saved anywhere.  

Does this is mean I have no file-backed rasters? Or is the problem related to the fact that this is not a "normal" `simList`?

**Comment by CeresBarros** [comment]
yes I can confirm that this is was partly the result of the `experiment2` call. 
My attempt with a with a (true) `simList` resulted in the creation of a `rasters` in the appropriate directory. But, no rasters were saved there and I have at least one file-baked raster:
```
> saveSimList(LandRBiomass_sim, file.path(simPaths$outputPath, paste0("simInitList_", runName)), fileBackend=1)

> inMemory(LandRBiomass_sim$rawBiomassMap)
[1] FALSE

> list.files(file.path(simPaths$outputPath, "rasters"))
character(0)

```

**Comment by CeresBarros** [comment]
here's a draft of something that could be implemented in `saveSimList` for class `simLists`
where `factorialSimulations` is a `simLists `object
```
lapply(names(factorialSimulations), FUN = function(x) {
  if (!x %in% c("._randomSeed", "._rng.kind")) {
  if (dir.exists(file.path(simPaths$outputPath, x))) {
    message("Saving ", x, " simList")
    saveSimList(factorialSimulations[[x]], 
                filename = file.path(simPaths$outputPath, x, paste0("simList_", x)),
                fileBackend = 1)
  } else {
    stop("directory doesn't exist")
  }
  }
})

```

**Comment by CeresBarros** [comment]
improvements on the code above:
```
lapply(names(factorialSimulations), FUN = function(x) {
  if (class(factorialSimulations[[x]]) == "simList") {
  if (dir.exists(outputPath(factorialSimulations[[x]]))) {
    message("Saving ", x, " simList")
    saveSimList(factorialSimulations[[x]],
                filename = file.path(outputPath(factorialSimulations[[x]]), paste0("simList_", x)),
                fileBackend = 1)
  } else {
    stop("output directory doesn't exist")
  }
  }
})
```

**Comment by eliotmcintire** [comment]
In the case where the user has called `experiment2(..., clearSimEnv = TRUE, outputs = data.frame(...))`, it seems like the user doesn't really need to be saving a series of `simList` files. Why don't they just save the `simLists` object, with no data in it, other than the metadata... so just `qs::qsave(factoricalSimulations)` will save the `simLists` object, and it will contain all the underlying `simList` metadata, just not any data in the `envir(sim)` because `clearSimEnv = TRUE` was set. 

I guess you are suggesting a way for people who did not use `clearSimEnv = TRUE` and didn't use `outputs = ...`, such as: 
```
factorialSimulations <- experiment2(..., clearSimEnv = FALSE, output = NULL)
```
Is it necessary to add a function for this use case?

**Comment by CeresBarros** [comment]
I did save the `simLists` object as you suggest (as `.rds`, not `.qs` however). And I think that's fine. But even with "empty" `simList` objects inside `simLists`, the object is very large. For instance, I'm running a small simulation of 30 years x 10 reps (with `experiment2(..., clearSimEnv = TRUE, outputs = data.frame(...))`) and the resulting `simLists` object is 

The reasons why I suggest implementing this behaviour are:
1) the case you mentioned, when users may want to have `simList` with it's objetcs and the size of `simLists` becomes prohibitive.
2) if `saveSimList` exists then `saveSimLists` should naturally be possible.

Now, given that the "solution" is so easy (e.g. the `lapply `I posted above) I'm all for being pragmatic and not making this because it's not essential. I just thought that IF we want to make this possible, that could be a way :)

Closing this issue

**Comment by eliotmcintire** [comment]
It seems like something is wrong... there is no way a `simList` can be 450MB if its "environment" is cleared. Can you check with `ls.str(factorialSimulations[[1]])` ?

**Comment by CeresBarros** [comment]
Somehow the subsetting with `[[` is not working properly, but here goes the result of `ls.str` (which is nothing?):

```
> ls.str(factorialSimulations[[1]])
Error in factorialSimulations[[1]] :
  wrong arguments for subsetting an environment
> names(factorialSimulations)
 [1] "sim1_rep01" "sim1_rep02" "sim1_rep03" "sim1_rep04" "sim1_rep05"
 [6] "sim1_rep06" "sim1_rep07" "sim1_rep08" "sim1_rep09" "sim1_rep10"
> ls.str(factorialSimulations$sim1_rep01)
```

**Comment by CeresBarros** [comment]
```
> file.size("R/SpaDES/outputs/dec2020Runs/sim1_rep01/simList_sim1_rep01")
[1] 76943857
```
Sorry, i just noticed that's 76 Mb, not 760! Oops

**Comment by eliotmcintire** [comment]
So the `simLists` class is indeed an environment, not a `list`... same as `simList` is not a `list`... yes, bad name. Can't change now. So, indexing with numeric doesn't work, as per the Error message.

76Mb is still a lot. A `simList` has several slots that are kept for metadata:

See here:
```
str(sim2, 2)
Formal class 'simList' [package "SpaDES.core"] with 12 slots
  ..@ modules  :List of 5
  .. ..- attr(*, "modulesGraph")='data.frame':	0 obs. of  2 variables:
  ..@ params   :List of 3
  ..@ events   :List of 2
  ..@ current  :List of 4
  ..@ completed:<environment: 0x564175cebd98> 
  ..@ depends  :Formal class '.simDeps' [package "SpaDES.core"] with 1 slot
  ..@ simtimes :List of 4
  ..@ inputs   :'data.frame':	11 obs. of  8 variables:
  ..@ outputs  :'data.frame':	0 obs. of  7 variables:
  ..@ paths    :List of 5
  ..@ .envir   :<environment: 0x5641e9614a60> 
  .. ..- attr(*, "name")= chr "sim"
  ..@ .xData   :<environment: 0x5641e9614a60> 
  .. ..- attr(*, "name")= chr "sim"
  ```

The only one of these that can "normally" get big-ish is the `completed` slot. As it just keeps adding elements to it. I guess `params` could be big-ish. But, check each manually. Below is one of mine that I am working on. `depends` is largest for me in this case:
```
> slots <- slotNames(sim2)
> names(slots) <- slots
> lapply(slots, function(sn) object.size(slot(sim2, sn)))
$modules
2088 bytes

$params
10992 bytes

$events
2296 bytes

$current
1136 bytes

$completed
56 bytes

$depends
40120 bytes

$simtimes
1456 bytes

$inputs
2888 bytes

$outputs
1704 bytes

$paths
1384 bytes

$.envir
280 bytes

$.xData
280 bytes
```

**Comment by CeresBarros** [comment]
Here's what I get:
```
> slots <- slotNames(factorialSimulations$sim1_rep01)
> names(slots) <- slots
> lapply(slots, function(sn) object.size(slot(factorialSimulations$sim1_rep01, sn)))
$modules
2728 bytes

$params
26976 bytes

$events
7888 bytes

$current
48 bytes

$completed
56 bytes

$depends
133352 bytes

$simtimes
1456 bytes

$inputs
2888 bytes

$outputs
7088 bytes

$paths
1560 bytes

$.envir
280 bytes

$.xData
280 bytes
```

Looks like `depends` is quite large compared to yours.

**Comment by eliotmcintire** [comment]
None of those is remotely close to 76 Mb.

Can you try same thing as above, but with `pryr::object_size` and `objSize` (ie each in turn and report) instead of `object.size`?

**Comment by CeresBarros** [comment]
```
> lapply(slots, function(sn) pryr::object_size(slot(factorialSimulations$sim1_rep01, sn)))
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
$modules
2.67 kB

$params
22.3 kB

$events
4.96 kB

$current
48 B

$completed
82.9 kB

$depends
104 kB

$simtimes
1.23 kB

$inputs
2.89 kB

$outputs
7.09 kB

$paths
1.56 kB

$.envir
2.73 GB

$.xData
2.73 GB
```
The outputs by `objSize` are very long, so I attached a .txt
[objSizeOut.txt](https://github.com/PredictiveEcology/SpaDES.core/files/5935737/objSizeOut.txt)

**Comment by CeresBarros** [comment]
closing this issue as it was confirmed that `saveSimList` won't work for `simLists` objects
