### ISSUE TITLE
loadSimList doesn't work with simLists from SpaDES.experiment::experiment2?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#140]
I saved the output `simList `from a `SpaDES::experiment2` call using `saveSimList` and see that a file with ca 3Gb has been created. However, loading it with `loadSimList `produces the following error:

```
> loadSimList(file.path(simPaths$outputPath, paste0("simList_factorialSimulations_", runName)))
Error in as.vector(x) :
  no slot of name "modules" for this object of class "simLists"
```

Note: When saving, I didn't add the file extension as per the documentation of `qs::qread`.

**Comment by CeresBarros** [comment]
I can confirm that this seems to be related to the fact that the `simList` was a result of an `experiment2` call, as I just tried to `saveSimList` and then `loadSimList` with an output of `simInit` and it worked fine.

**Comment by eliotmcintire** [comment]
Note the difference between `simLists` class (with an "s") and `simList` ... the `simLists` class is just a list of `simList` objects, so can be used, manipulated, accessed accordingly. There are currently no methods for `simLists` class.
