### ISSUE TITLE
feature request: run only `init` events

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#144]
`experiment(2)` can run into cache saving/loading issues when running in parallel and caching is usually more heavily used during `.inputObjects` and `init` events. A work around to avoiding these cache issues is to run the first year of the simulation before launching `experiment`, e.g.:

```
simAfterDotInputObjects <- simInit(times = list(start = yearStart, end = yearStart), ...)
simInitAfterInit <- spades(simAfterDotInputObjects)
end(simInitAfterInit ) <- yearEnd
experiment2(simAfterInit, ...)
```
It would be nice, if we could prevent the whole first year from running in the `spades` call and just run all the `init` events. then `experiment2` would continue from the scheduled events.

**Comment by eliotmcintire** [comment]
It is impressive that this has never come up before...

**Comment by eliotmcintire** [comment]
Possible approach. An `events` argument for the `spades` call. Would be a list of named elements, with "name" being the module name, and the elements being a character vector of events to run in that module. There could easily be a wrapper function ... e.g., `spadesInitOnly` that is a special case: run init events for all modules. Maybe don't need anything specific for `experiment2` ... see example:
```
# underlying mechanism allows for great flexibility
sim <- simInit(modules, params, inputs, outputs)
eventsForSpades = list(
    Biomass_borealDataPrep = "init",
    Biomass_core = c("init", "plot")
)
simPostInit <- spades(sim, events = eventsForSpaDES)

# Or with one of 2 alternate wrappers when just inits
## option 1 -- 2 step
sim <- simInit(modules, params, inputs, outputs)
simPostInit <- spadesInitOnly(sim, events = eventsForSpades)

## option 2
simPostInit <- simInitAndSpadesInitOnly(modules, params, inputs, outputs) 
# or
simPostInit <- Cache(simInitAndSpadesInitOnly, modules, params, inputs, outputs) 

# Would work well for experiment
expOut <- experiment2(simPostInit) 
expOut <- simInitAndExperimentInitOnly(modules, params, inputs, outputs) 
expOut <- Cache(simInitAndExperimentInitOnly, modules, params, inputs, outputs) 


```

**Comment by CeresBarros** [comment]
Personally, I don't see the needs for wrappers so much and prefer having `spades` handle the choice of events. In this case,  `simInitAndSpades` and `experiment` would accept the `events` argument and pass it to their `spades` call.

**Comment by eliotmcintire** [comment]
Put yourself in Tati's shoes ... if you have 25 modules. That is a long list of just typing "init", "init", "init", etc. ... but regardless, those wrappers are the easy part. 

I think your suggestion lead to ambiguity. It is not that you only want certain events sent to `experiment`, but that you want certain events "run once" in `experiment`. So, as I worked through the possibilities, I think that is the most difficult to express precisely in a single `experiment2` call. 

The 3 step is precise and clear, i.e., which parts are run once and which are run multiple times: `simInit |> spades |> experiment2`.

For the sake of `Cache`, wrapping these into an "all in one" step is essential ... `simInitAndExperimentInit`.

**Comment by CeresBarros** [comment]
In your two first options/examples the user has to define `eventsForSpades` when using the wrapper `spadesInit`, so it wasn't clear to me why the wrapper `simInitAndSpadesInit` and `simInitAndExperimentInit` are absolutely needed. 

I'm also a bit confused wrt the behaviour of `spadesInit` and `simInitAndSpadesInit`.
Are you saying that the wrapper `simInitAndSpadesInit` will assume only `init` events are to be run, but  `spadesInit` needs that `events` list?

I also don't see how what I said leads to more ambiguity than `simPostInit <- spades(sim, events = eventsForSpaDES)` I merely expressed that I found this to be enough. 
However, given the example of "many modules" that you mentioned, I think you're right in that a `spadesInit` function that _by default_ will only run the `init` events (but can run more if user supplies `events` list) is useful

**Comment by eliotmcintire** [comment]
See edit in initial post. Indeed you spotted a typo. The wrapper `spadesInit` doesn't specify the events.

**Comment by achubaty** [comment]
@eliotmcintire does #146 now cover this?

**Comment by eliotmcintire** [comment]
Implemented in `development` branch.  Both of these below work. There is no wrapper, and nothing explicit for `experiment2`, and no compound functions such as ~`simInitAndSpadesInit`~

```
spades(sim, events = "init")
# or
spades(sim, events = list(Biomass_borealDataPrep = c("init", "plot"),
                          Biomass_core = "init"))
```

**Comment by CeresBarros** [comment]
brilliant, will test soon!
