### ISSUE TITLE
restore Sys.info() to simList

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#15]
_From @achubaty on March 14, 2017 20:4_

Was removed in a2e46f618a5d789baa953bf836871a2b60489251 because the system call caused AWS to give an "out of memory" error and crash.

Need to identify whether this is an issue with R on systems with user limits enabled, or perhaps something else.

_Copied from original issue: PredictiveEcology/SpaDES#338_

**Comment by eliotmcintire** [comment]
Can we just leave this and close issue @achubaty ?  I think this is not a necessary part of a `simList`. It will require idiosyncratic behaviour with `Cache` (though doable); but more, this is a session-specific information. If a `simList` gets saved and loaded on a different computer or different R version, that is OK. I am closing this.
