### ISSUE TITLE
saveSimList() using fileBackend > 0 fills /tmp (potentially crashing machine)

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#157]
Reprex to follow in a few weeks, but there are possibly a few issues at play here, and I'm not sure if it's a `SpaDES.core` or `reproducible` issue.

```r
saveSimList(... fileBackend = 0) ## works, but is not portable
saveSimList(... fileBackedDir = "somewhere", fileBackend = 1) ## fails per below
saveSimList(... fileBackedDir = "somewhere", fileBackend = 2 ) ## fails per below
```

Trying to use `fileBackend` > 0 is filling up the session Rtmp directory, specifically a subdir used by `reproducible`.

```
~/GitHub/WBI_fireSense$ ls -la /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/*
-rw-r--r-- 1 achubaty achubaty       1829 Mar 10 14:09 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 10 14:09 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked.gri
-rw-r--r-- 1 achubaty achubaty       1829 Mar 17 12:56 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_1.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 17 12:56 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_1.gri
-rw-r--r-- 1 achubaty achubaty       1829 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_10.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_10.gri
-rw-r--r-- 1 achubaty achubaty       1829 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_11.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_11.gri
-rw-r--r-- 1 achubaty achubaty       1829 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_12.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_12.gri
-rw-r--r-- 1 achubaty achubaty       1829 Mar 17 12:58 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_13.grd
-rw-r--r-- 1 achubaty achubaty 6209834400 Mar 17 12:59 /tmp/Rtmp5FgMvM/Require/1dan1FiZKDp/MB_projMDC_lcc_masked_13.gri
...
...
```

Possibly related:

1. `saveSimList()` isn't identifying rasters in a list as needing to be copied (see https://github.com/PredictiveEcology/SpaDES.core/blob/development/R/save.R#L275)
2. `Copy`ing the sim list appears to be the issue, but it's unclear why since Eliot says "`reproducible::Copy` is recursive ... and taps into the same mechanics as `Cache` i.e., `.prepareFileBackedRaster`"

**Comment by eliotmcintire** [comment]
That line might be the culprit ... all the backend stuff (`Copy` etc.) all are fine ... but that line will be missing the nested rasters.

**Comment by achubaty** [comment]
Additional info:

- setting `options(reproducible.tempPath = "blah")` doesn't affect the usage of `/tmp` (i.e., it uses a different random Require tmp location anyway)
- caching _per se_ doesn't seem to have this issue -- I see hardlinked files in the cache directory but note the absence of hardlinks in the `ls` output above (the `1` after the file permissions indicates the number of refs pointing to that file).

**Comment by achubaty** [comment]
Eliot had resolved the the primary issue (using `fileBackend = 2` doesn't crash), but some of the secondary issues need to be followed up on.
