### ISSUE TITLE
mod$ variables created during .inputObjects not keptwith caching

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#159]
When `mod$` variables are created in `.inputObjects` they are not kept after caching and retrieving cached `.inputObjects` calls.  This is presumably because caching is doing a clean-up of objects not declared as inputs/outputs  in the module metadata. Maybe intended, but opening an exception to `mod$` objects would be useful.

**Comment by eliotmcintire** [comment]
The `mod` should be brought along with `Cache` as it is part of the hidden objects in a module, which are all carried along with a `Cache`.  I will close this; if it is still an issue somehow, we can re-open and debug with a reprex.
