### ISSUE TITLE
Changing end(sim) to lower value on a simList from simInitAndSpades(..., events = "init") doesn't work

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#161]
I have the feeling that running `simInitAndSpades(..., events = "init")`  is having some strange repercussions that I can't put my finger on. I keep having this "silent fail/error" or "nothing happens" behaviour when I try to do things like change end(sim) before running spades (after generating a `simList  `with `simInitAndSpades(..., events = "init")` ).

```
## where LIM_simInitList is a list of 2 simList objects
> test <- LIM_simInitList[[1]]
> end(test) <- 50L
> spades(test)
Mar24 09:45:08       Resetting .Random.seed of session because sim$._randomSeed is not NULL. To get a different seed, run: sim$._randomSeed <- NULL to clear it.
simList saved in
 SpaDES.core:::.pkgEnv$.sim 
It will be deleted at next spades() call.
## ^^ nothing happens

> test <- LIM_simInitList[[1]]
> spades(test)
## runs fine
```

I know that the init event schedules a bunch of things, but it's not clear to me why changing `end(sim)` after running `init` (only)  would be any different from changing `end(sim)`  after, e.g. running 10 years of simulation and prolonging it for another 10, or changing `end(sim` to a lower value after running `.inputObjects` (only) - like in a "normal" `simInit` call.

So I tried changing to a "higher" `end(sim)`  than what was set during `init`:

```
test <- LIM_simInitList[[1]]
end(test) <- 102L
spades(test)
## runs fine (!)
```

So the question is: is this intended behaviour?

**Comment by eliotmcintire** [comment]
This is happening because the `time(sim)` that spades is seeing is actually 100 at the end. So, it won't even start any of the events in the event queue, when you restart it even though they appear to your eyes as "before" `end(sim)`. The way spades knows that `time(sim)` it is is by first looking at the current value of time(sim), then by running the next event in the event queue, if `time(sim) < end(sim)`. In your case, it fails that test, `time(sim) > end(sim)` so it doesn't start the event queue. If it did start the event queue, then it would update `time(sim)` with the time of the event it is doing.

So, as a work around, you should change `time(sim)` too.  

Not sure if this is a bug... I guess it may be "correct" behaviour to look at the event queue to get current time. Currently, it _has_ a value in the `time(sim)` and it is the value it had at either previous event or `end` (your case here)

**Comment by CeresBarros** [comment]
I just noticed this:
```
test <- LIM_simInitList[[1]]
end(test)
[1] 100
attr(,"unit")
[1] "year"
end(test) <- 102L
spades(test)
(...)
> end(test)
[1] 102
attr(,"unit")
[1] "year"
> time(test)
[1] 100
attr(,"unit")
[1] "year"
```

basically, the simulation didn't run all the way to the "new" `end(sim)`. Is this also intendeed?

**Comment by CeresBarros** [comment]
I think I understand why "the simulation didn't run all the way to the "new" end(sim)" now. It's because the init events didn't scehdule anything for `end(sim) + 1L` like a "normal" `spades() `call does.

**Comment by CeresBarros** [comment]
What is less clear to me is why `time(sim) = 100L` (instead of 1L) after running only the `init` events.

**Comment by CeresBarros** [comment]
Also:
```
> time(test) <- 1L
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘time<-’ for signature ‘"simList"’
 ```
 How should do I do the workaround you suggested?

**Comment by CeresBarros** [comment]
Found it:
```
> SpaDES.core::times(test)$current <- 1L
```

But not sure why `time(sim) <- value` isn't working... the doumentation suggests it should

**Comment by eliotmcintire** [comment]
> What is less clear to me is why time(sim) = 100L (instead of 1L) after running only the init events.

This has to do with how the events are run and not run in `events = "inits"` ... basically, it doesn't affect the time part, it runs the entire time through all the events until `end(sim)`. It just limits the events that can be scheduled to those indicated. It doesn't change anything about `time(sim)`.

**Comment by eliotmcintire** [comment]
It is likely incorrect behaviour to override `simInit(..., times = list(start = 0, end = 100), ...)` because only events that ran in year 0 occurred. `end` is the _end_

**Comment by eliotmcintire** [comment]
Need to ensure that the `setReplacement` method is indeed implemented correctly for `time`

**Comment by CeresBarros** [comment]
what do you mean? we often talked about this being a feature of SpaDES:
```
simListt1 <- simInit(..., times = list(start = 0, end = 10))
simOut <-  spades(simList1)
end(simOut) <- 15
simOut <- spades(simOut)
```
is it because in the above we're changing `end(sim)` of `simOut`, rather than `simList1` (like I was doing)?

**Comment by eliotmcintire** [comment]
`end<-` is obviously working; but it looks like `time<-` is not.

**Comment by eliotmcintire** [comment]
I believe the "correct" behaviour for your use case is to update the original `time = ...` in the `simInit` so that it only runs to the year your events are in:
```
simOut <- simInitAndSpades(..., times = list(start = 0, end = 0), events = list("init"))
end(simOut) <- 100L
simOut <- simInitAndSpades(simOut)
```

**Comment by CeresBarros** [comment]
I see, thanks!

**Comment by eliotmcintire** [comment]
Perhaps what should happen is a check for any events in the queue that are prior to the `time(sim)` at the first event of a `spades` call. This would result in the behaviour you were expecting, and it would be consistent with the "within spades call" behaviour ... ie., if there is an event that is prior to `time(sim)`, it will update `time(sim)` to be "before".

**Comment by eliotmcintire** [comment]
See update in 958c824953de5ee7063678f22f90d59cc24a96b6. This implements the above.

**Comment by eliotmcintire** [comment]
This should now be fixed in @development
