### ISSUE TITLE
downloadModule/downloadData should check for local files before checking remotely for download

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#17]
_From @achubaty on November 7, 2016 23:13_

Although the files exist locally, `downloadModule` is still checking for the existence of the module remotely for download.

This is a bigger problem with GitHub's API rate limits because only a few calls to `downloadModule` are needed to trigger a 403 error. The `checkModule()` call early in the `downloadModule()` function is being called without first checking to see whether files exist locally. It's worth implementing a local check/checksum for module code, in addition to the checks for downloading data.

_Copied from original issue: PredictiveEcology/SpaDES#319_

**Comment by achubaty** [comment]
_From @eliotmcintire on November 7, 2016 23:14_

@melinahoule This may be relevant to our discussions today

**Comment by achubaty** [comment]
note that my changes made in 3e56cf9 aren't checksumming or doing anything special when checking for local copies of modules -- just looking for a presence of a few files and checking the version. this should be made more robust.

**Comment by eliotmcintire** [comment]
Closing -- low priority -- labelling "Not Done"
