### ISSUE TITLE
GDAL 3.3.2 example failure

### ISSUE THREAD

**Issue by rsbivand** [PredictiveEcology/SpaDES.core#174]
[00check.log](https://github.com/PredictiveEcology/SpaDES.core/files/7097858/00check.log)

From revdeps with PROJ 8.1.1 and GDAL 3.3.2, the package fails in the outputs examples:

```
>       newRas <- raster(dir(tmpdir, full.name = TRUE, pattern = ".tif"))
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.
In addition: There were 14 warnings (use warnings() to see them)
> dir(tmpdir, full.name = TRUE, pattern = ".tif")
[1] "/tmp/RtmpvjXEpt/outputs/test_year10.tif"        
[2] "/tmp/RtmpvjXEpt/outputs/test_year10.tif.aux.xml"
> newRas <- raster(dir(tmpdir, full.name = TRUE, pattern = ".tif")[1])
>       all.equal(newRas, ras) # Should be TRUE
```

So `dir(tmpdir, full.name = TRUE, pattern = ".tif")` now returns two file names, which `raster()` cannot disambiguate. I think the code has always been fragile, so choosing the first element disambiguates.

**Comment by achubaty** [comment]
@rsbivand  thank you for identifying this, I have made the change you suggested. I'll try testing with latest GDAL when I get a moment. Is there a docker container or similar you are using for testing?

**Comment by rsbivand** [comment]
I don't use docker, should sometime, but am concentrating on release candidates installed from source. PROJ 8.1.1 is just released https://download.osgeo.org/proj/proj-8.1.1.tar.gz, GDAL 3.3.2RC3 https://download.osgeo.org/gdal/3.3.2rc3/gdal-3.3.2rc3.tar.gz, but the problem may have existed before in the PROJ 8.1 and GDAL 3.3 branches; looking at my logs it was there for PROJ 8.1.0 with GDAL 3.3.1 RCs, but I didn't follow up then, as looking for **s2** problems, which this wasn't.

**Comment by achubaty** [comment]
currently passing macOS 11.5.2, R 4.1.1, with GDAL 3.3.1 and PROJ 8.1.1.

will test again once `brew` updates the GDAL formula to use 3.3.2
