### ISSUE TITLE
implement 'futures' for asynchronous computing?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#18]
_From @achubaty on November 3, 2016 17:18_

See [here](https://alexioannides.com/2016/11/02/asynchronous-and-distributed-programming-in-r-with-the-future-package/) for a nice overview of how it could be used.

`future` package here: https://github.com/HenrikBengtsson/future

I can see this coming in handy for downloads, GIS operations, etc. which would normally block the main process -- these can be computed in a new process.

_Copied from original issue: PredictiveEcology/SpaDES#317_

**Comment by achubaty** [comment]
even if we don't implement this in the package, this is likely still useful for module development.

**Comment by achubaty** [comment]
_From @eliotmcintire on November 3, 2016 17:41_

We had talked about this before. I think it is _necessary_ for us to implement in the main DES of SpaDES.  Basically, when the DES comes across conditionally independent modules, it should automatically run them with the future function, so that two or more module events can run concurrently. The details of this will be somewhat complicated, as conditional independence will be sometimes difficult to establish. But in principle, it should be implemented.

Quote from [here](https://en.wikipedia.org/wiki/Discrete_event_simulation):

> A more recent method is the three-phased approach to discrete event simulation (Pidd, 1998). In this approach, the first phase is to jump to the next chronological event.  The second phase is to execute all events that unconditionally occur at that time (these are called B-events).  The third phase is to execute all events that conditionally occur at that time (these are called C-events). The three phase approach is a refinement of the event-based approach in which simultaneous events are ordered so as to make the most efficient use of computer resources. The three-phase approach is used by a number of commercial simulation software packages, but from the user's point of view, the specifics of the underlying simulation method are generally hidden.

**Comment by achubaty** [comment]
Agreed (just wanted to document it here). It will take some work, but we already know the direct module dependencies so figuring out unconditionally co-occuring events should be doable. The indirect dependencies will be tricky to sort out though.

**Comment by achubaty** [comment]
_From @eliotmcintire on November 3, 2016 18:8_

Easy types of module to deal with are **summary-type** modules and, more generally, modules with **no-feedbacks**. For ease of expressing the idea, we can call these **branch tip modules**. We can identify these modules with no feedbacks because _no other module has inputs that match with these_ **branch tip module** _outputs_.

So, for example, a wildlife module in which all events require inputs from other modules (e.g., to take the habitat maps), but there are no feedbacks into the system (the other modules are not affected by any of the module outputs) because nothing that the wildlife does will affect any other modules.

These will be a good first type to deal with.

Having said that, I think I just worked through how to do it for  _indirect dependencies_ (see below).

I believe the work flow would be this:
- If one of these modules is scheduled to run, it's `doEvent` is spawned inside a future( ) call 
- its valuation is forced at some time in the future (by calling `value( )`). I believe there is no actual requirement that it be valued at any particular time since its outputs are not required by anything else. 
- Possible sensible times to call `value` would be at 
  - `end(sim)` (the most computationally efficient because no other events will be conflicting at that point -- could be dangerous with infinite loop possibility, see next point)
  - at the next call to that same module-event (while not essential, this is aesthetically nice as it means we can't create an infinite loop)
  - in the case of _indirect dependencies_, we can assess dependencies at each doEvent and if the any preceding _future_ call had an output dependency that matches one of the input dependencies, then it forces a call to `value( )` before proceeding.

**Comment by achubaty** [comment]
For events this may be tricky because our pattern is `sim <- myEvent(sim, ...)`, which means subsequent modifications of sim may not be possible while it's being evaluated in a future.

The result object needs to be separate from the `sim` object, so that the simulation can proceed without needing to put the result into the simlist. but even so, Ii don't know that it's possible to make the simList itself a future, and add multiple futures to it as objects. So any futures may need to be assigned somewhere else, and those values checked at the end of the simulation.

**Comment by eliotmcintire** [comment]
I advanced a bunch ... but there are several cases I hadn't thought of that are still unresolved. Leaving for now.
Latest: e575b16d5baa9198049a007f019ce7e6007ee94b

**Comment by eliotmcintire** [comment]
I was using the 3 sample modules as test cases. The `caribouMovement` is one whose outputs are not required by other modules. This part is implemented. 

#### Unknown Self Scheduling
The other component that was sneaky is that a module (e.g., `caribouMovement`) might be scheduling itself for a time _before_ the next "other" module. In this case, it has 1 input dependency, `landscape`. While the caribou module doesn't produce anything that another module needs (e.g., no `createsOutput` that another module has as `expectsInput`), it does need the `landscape` again and again and again, _before_ `landscape` changes. But we don't know this until the first instance runs and schedules the next instance. In this case, `caribouMovement` runs monthly, and so will run 12 times for each `fireSpread` module. 

##### Solution
Test if Module A has scheduled itself at the top of `doEvent`, to enable rearranging of the event queue before it gets changed by the event in Module B that can't be run until Module A is completed. I have begun this : a12b5800ea83766703cfed9b005649ad5d689280

**Comment by eliotmcintire** [comment]
Still to do:
Get `test-useFuture.R` working

**Comment by eliotmcintire** [comment]
Pulled into `development` for further testing. 405f9a64e7b2629b785515c59286155f93f99207
