### ISSUE TITLE
Errors using newModule() and newModuleCode()

### ISSUE THREAD

**Issue by chrismallon** [PredictiveEcology/SpaDES.core#186]
Hello folks,

Thanks as always for all the work you do on SpaDES! I was attempting to make a new module, as described in [SpaDES 4 Dummies](https://htmlpreview.github.io/?https://github.com/CeresBarros/SpaDES4Dummies/blob/master/SpaDES4Dummies.html). I ran the following code, and received errors:
```
SpaDES.core::newModule("scfm_dataPrep", 'modules')
Error in file(con, "r") : invalid 'description' argument
```

```
SpaDES.core::newModuleCode("scfm_dataPrep.R", path = 'modules/scfm_dataPrep')
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘newModuleCode’ for signature ‘"character", "character", "missing", "missing", "missing"’
```

`newModule` successfully creates `data` and `R` directories in the target path, but then it fails. Here is my `SpaDES.core` package version:
```
packageVersion('SpaDES.core')
[1] ‘1.0.9.9008’
```

Thanks for your help!

**Comment by achubaty** [comment]
can you please confirm that your working directory contains a `modules/` subdirectory?

**Comment by chrismallon** [comment]
Hi All,
After a restart the code now seems to be running. Path gremlins? To answer Alex's question, there was a `modules` directory, but I can't fully explain why the code failed to run.

Again, seems to be fine now. Thanks!
