### ISSUE TITLE
care needed with special simList accessors (environments + active bindings)

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#196]
After a bunch of debugging trying to get simulations to run on a cluster, here are some gotchas to look out for when using certain "special" accessors inside global scripts:

1. `P(sim)$moduleName$paramName` works fine in a module but `P(mySim, "paramName", "moduleName")` needs to be used;
2. `Paths` is a no-go. If using `setPaths(listOfPaths)`, then use `listOfPaths` directly instead of `Paths`.

Related to paths: I need to manually pass a filename for the `debug` log file in `simInit()` because the default it was using kept being from the main thread's output path instead of using the worker's.

**Comment by eliotmcintire** [comment]
Can you please confirm that this is still happening?
