### ISSUE TITLE
getting/setting default working directory options

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#20]
_From @achubaty on October 11, 2016 19:42_

Commits 90624d9c and 5c6f83d8 implement two functions to get and set the default path options (_i.e._, global defaults for simulation working directories).
1. The current implementation of `setPaths` won't let you change paths one at a time -- it resets the paths you're not trying to set to the defaults (fixed in https://github.com/PredictiveEcology/SpaDES/commit/9bfb8d55214cb7bf8e0a9e6aedbb5f5eabf4d555).
   
   Once this is fixed, `setPaths()` with no arguments becomes redundant with `getPaths()`, so I can see it being removed and `setPaths` being renamed. Is `defaultPaths` the best name for this function??
2. Non-standard R options set by the user (_e.g._, those set by R packages) are not persistent across sessions. Therefore, the user needs to reset the default paths each time they load R, so our documentation needs updating to show loading the package as follows:
   
   ``` r
   library(SpaDES)
   setPaths()
   ```

_Copied from original issue: PredictiveEcology/SpaDES#314_

**Comment by achubaty** [comment]
_From @eliotmcintire on October 24, 2016 16:23_

@achubaty Current behaviour doesn't seem desireable:

After setPaths(modules = "desired/path"), paths are set correctly, but do not persist through restart.

**Comment by achubaty** [comment]
_From @eliotmcintire on October 24, 2016 16:28_

@achubaty Also, in `simInit`, any path not specified by user and passed explicitly to `paths =` arg defaults to active directly, which is not the correct behaviour. I think the correct behaviour is to have spades paths override the active directory. 

Order of precedence in the `simInit` should be, from highest to lowest:
1. paths argument
2. spades.xxxPath
3. if spades.xxxPath is NULL, then active directory

**Comment by achubaty** [comment]
@eliotmcintire yes, I noted that above. R options (the non-standard ones at least) are not persistent across sessions. Aside from updating all of our docs to teach setting the paths after loading the package, per above, how else can we improve this? Using the current working directory (as we had done previously) is also undesirable.

**Comment by achubaty** [comment]
> @achubaty Also, in `simInit`, any path not specified by user and passed explicitly to `paths =` arg defaults to active directly, which is not the correct behaviour. I think the correct behaviour is to have spades paths override the active directory. 
> 
> Order of precedence in the `simInit` should be, from highest to lowest:
> 1. paths argument
> 2. spades.xxxPath
> 3. if spades.xxxPath is NULL, then active directory

Hmm, I'm not sure why it's defaulting to the current dir. Sounds like the paths set by the options weren't fully implemented everywhere. I'll take a look.

**Comment by achubaty** [comment]
_From @eliotmcintire on October 24, 2016 16:37_

What about wrapping this in the setPaths() function:

assignInNamespace(ns = "SpaDES", x = ".defaultPaths", value = paths)

Then, instead of using options, we are actually using the SpaDES namespace. I think that is allowed because it is a SpaDSE function that is doing it. Then, instead of using "options", we just use an object called `SpaDES:::.defaultPaths`

That seems to be persistent, at least on Windows. There may be issues on Linux if the package was installed by someone other than the user.

**Comment by achubaty** [comment]
_From @eliotmcintire on October 24, 2016 16:45_

Apparently that is not persistent

**Comment by achubaty** [comment]
Yes, that might work -- when the namespace is reloaded does it keep those values?

Another option is to read/write from/to an options file, but it's not clear where this should be saved. Using the home dir in this case might be fine because the write operation would be invoked only by the user using `setPaths()`.

**Comment by achubaty** [comment]
see also https://github.com/gaborcsardi/pkgconfig

**Comment by eliotmcintire** [comment]
Now fully revamped, removing `spades.cachePath`  7e82ccf839aa24f280b8114e5f612df092ee9ac7 and allowing multiple `modulePath` values 2ee5f26ce424ac37a3fa3157d8f0a64aa0b93517. 

Also, during `simInit` and `spades` calls, the 4 paths are set in the options are using `setPaths`, then reset to former options `on.exit` from both of these.
