### ISSUE TITLE
create .wrapup event to run at end of simulation

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#209]
Opening for further discussion: is it worth creating a special event akin to .inputObjects that is run at the end of a simulation?

My rationale stems from the fact that spades() doesn't check for creation of output objects declared in module metadata.

Even though spades() doesn't know when a module is done it does know when the sim is done. A late error is still better than no error. Should be easy enough to check for the objects and match their types.

I can imagine that .wrapup could be used to :

1. Check output creation and correct types
2. Could be used to trigger additional plotting or saving — eg we manually check the simulation time when creating plots in B_core. Would it be useful to have this as a general feature?
3. Would allow additional tasks like zipping outputs or prepping for postprocessing — especially useful for sim wrap up, not just at module level.

**Comment by eliotmcintire** [comment]
I'll let this sit for a bit, but I don't quite see the use cases. 

> Would allow additional tasks like zipping outputs or prepping for postprocessing — especially useful for sim wrap up, not just at module level.

The beginning of a module is well defined (the `init` event always runs), but the end is not. I don't see the value in doing things like zipping/tarring outputs at the module level; that is more whole model level. 

> Check output creation and correct types

This could be incorporated into `spades`, checking the classes of `createsOutput` after each event is complete, though that would add considerable computational time in cases with many rapid events with many objects. There would be ways to keep this light-ish...

Plotting and Saving, I believe, is better as modular function calls e.g., `Plots` and `outputs` that can be controlled at the model call (e.g., `spades` or `simInit`).

I could see the value in a `spades`-level wrap up check of some things like `class` ... and maybe a more formal "wrapup" something. But seems like even that would be better to do something more general that would work for the common case of replicated `spades` calls too...

**Comment by achubaty** [comment]
uploads / archiving to continue being handled at module/project level.
