### ISSUE TITLE
improved param checking in modules

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#21]
_From @achubaty on September 16, 2016 14:45_

@eliotmcintire
- [ ] update `checkParams()` to include checks for `P(sim)` usage
- [ ] fix false positives when lines are commented out (include a grep for whitespace + `#` at the beggining of a line)
- [ ] when a parameter is defined within the parameters list (and passed to `simInit`) that does not exist in the module metadata, the `show` method for the `simList` object does not work. See the `mapply` call of `simList-accessors.R` (was line 56) .

_Copied from original issue: PredictiveEcology/SpaDES#302_

**Comment by achubaty** [comment]
@SteveCumming thanks for spotting the 'commented out lines generate false positives' bug. added to the list above

**Comment by achubaty** [comment]
_From @SteveCumming on October 25, 2016 18:17_

My pleasure. Thanks for helping out today.

**Comment by eliotmcintire** [comment]
Closing -- low priority. Labelled NotDone.
