### ISSUE TITLE
inform user when event isn't scheduled

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#22]
_From @achubaty on September 16, 2016 14:23_

From Glenn Sutherland:

> If an event is defined, but never scheduled, ... it will never appear in the `events()`, `completed()` or `current()` lists. The developer therefore figures out by:
> 1. something isn't being done as expected
> 2. by inspecting the various event queues, and noticing the absence of a particular event. 
> 
> This is fine, but in effect you have to infer (by subtraction) that something isn't happening that you intended to be happening, and that the problem is you failed to schedule it. ...
> 
> Suggestion: Since SpaDES know the event is there via `simInit()`, why not have it explicitly make a default state of "NS", and have it appear in the events() queue with that state, if in fact it has not been scheduled. This would make the problem immediately apparent, and is therefore more transparent.

_Copied from original issue: PredictiveEcology/SpaDES#301_

**Comment by achubaty** [comment]
This is a good idea, but I think that rather than put these events into the events queue with a special state, we can provide a message to the user (like we do for unused parameters) that an event is defined but there is no corresponding `scheduleEvent()` call for that event.

**Comment by achubaty** [comment]
This could be neatly added once `defineEvent()` is implemented (#316). During `simInit`, grep for `defineEvent()` and `scheduleEvent()` calls and match them up.

**Comment by eliotmcintire** [comment]
Closing -- apparently not important enough. Adding tag "Not Done"
