### ISSUE TITLE
Require::getPkgVersions() removed upstream

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#229]
`Require` v0.2.6 removed `getPkgVersions()` (https://github.com/PredictiveEcology/Require/commit/ce658b13371049917a786eedfc2dbd8847ad5d05; https://github.com/PredictiveEcology/Require/commit/b7997cc4a416845a5c4081d57c5f769c093f5075).

@eliotmcintire why was it removed in the first place? No info provided in those commit messages. This is blocking CRAN submission of `SpaDES.core`.

Options:

1. restore `getPkgVersions()` to `Require` (would need a new submission; might be too soon after the most recent one);
2. identify a replacement function in `Require` package that does what the function was doing, and use this is `SpaDES.core` instead;
3. copy the removed function into `SpaDES.core`.

**Comment by eliotmcintire** [comment]
Something is wrong. I dealt with this on both.

**Comment by achubaty** [comment]
**NOTE**: the master branch (v0.2.6 tag) does _not_ work -- need the version from CRAN

**Comment by achubaty** [comment]
I have re-tagged Require v0.2.6 to the correct commit to match the CRAN version
