### ISSUE TITLE
improve error/warning messages throughout SpaDES

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#23]
_From @eliotmcintire on May 13, 2015 17:8_

Known places:

- [ ] When an object is missing, usually not created from a different module: 
  
  > Error in (function (classes, fdef, mtable)  :
  >  unable to find an inherited method for function ‘spTransform’ for signature ‘"NULL", "CRS"’ 

_Copied from original issue: PredictiveEcology/SpaDES#183_

**Comment by achubaty** [comment]
were these dealt with? I thought we had fixed the first one...

**Comment by achubaty** [comment]
_From @eliotmcintire on January 4, 2016 20:19_

Not sure. Needs testing.

**Comment by achubaty** [comment]
see the `checkmate` package (https://mllg.github.io/checkmate/articles/checkmate.html) to implement this is a way that's both fast and doesn't require much additional code

**Comment by eliotmcintire** [comment]
Closing ... apparently low priority. I will tag with "NotDone"
