### ISSUE TITLE
sporadic download failures triggering test failure

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#237]
This is happening consistently on CRAN check machines, and frequently in my local tests. (with #225)

```r
── Failure ('test-downloadModule.R:152'): downloadModule does not fail when data URLs cannot be accessed ──
`d` not equal to `d_expected`.
Lengths differ: 0 is not 2
```

**Comment by achubaty** [comment]
note this is hapenning usinsg development branch of `reproducible` (not the CRAN version)

**Comment by eliotmcintire** [comment]
How is this happening on `CRAN check machines`. The test has `skip_on_cran`?

**Comment by eliotmcintire** [comment]
Is this still happening? @achubaty Can you please work on this as you are seeing it in the wild. `SpaDES.core` `2.0.0` is being submitted shortly to CRAN. Any fix for this can be on next release.

**Comment by achubaty** [comment]
haven't seen this with the latest updates. closing.
