### ISSUE TITLE
don't install packages during tests

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#238]
E.g., when `fastdigest` wasn't previously installed, I get the following note during tests:

```r
❯ checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    ‘fastdigest’
```

Installing `fastdigest` and then running tests clears the note, but we shouldn't be installing anything during tests - this not allowed by CRAN.

**Comment by eliotmcintire** [comment]
Do you have any idea where this is happening? Obviously there is no `fastdigest` in this package, so some dependency is doing something?

**Comment by eliotmcintire** [comment]
Adding `fastdigest` as a `Suggests` is a work around. This package doesn't use it. I don't think that is a good suggestion.

**Comment by eliotmcintire** [comment]
This no longer appears; `fastdigest` has been removed and there are no references to it in tests.
