### ISSUE TITLE
add conditional/optional module object dependencies

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#24]
_From @achubaty on April 24, 2015 21:1_

indicate which modules "enhance" exisitng modules through use of modules designed to be used together (see #176).

these optional deps should be indicated by dashed line in `depsGraph` plot.

_Copied from original issue: PredictiveEcology/SpaDES#180_

**Comment by eliotmcintire** [comment]
Closing -- low priority
