### ISSUE TITLE
error when saving several objects with ``saveFiles()`` and ``.saveObjects``

### ISSUE THREAD

**Issue by mbelkebrea** [PredictiveEcology/SpaDES.core#241]
I want to save several objects with the ``saveFiles()`` function. And this works fine as long as I have only one object that I want to save. For example, in the the simParams list I define ``saveObjects=c("lichenRaster")`` and this executes correctly when passed to ``simInit()`` and then ``spades()``.
Problems happen when I try to save two objects, for example ``.saveObjects=c("lichenRaster", "vegTypeMap")``. I get the following error:

``Error in data.frame(objectName = ., saveTime = curTime, file = ., stringsAsFactors = FALSE) :
arguments imply differing number of rows: 2, 1``

Ceres managed to reproduce the error and will follow up with a reproducible example.

**Comment by CeresBarros** [comment]
Here's a reprex:
```
Require::Require("CeresBarros/SpaDES.core@test (HEAD)", 
                dependencies = FALSE, update = FALSE, force = TRUE)

#' # This will save the "caribou" object at the save interval of 1 unit of time
#  in the outputPath location
outputPath <- file.path(tempdir(), "test_save")
times <- list(start = 0, end = 6, "month")
parameters <- list(
  .globals = list(stackName = "landscape"),
  caribouMovement = list(
    .saveObjects = c("caribou", "habitatQuality"),
    .saveInitialTime = 1, .saveInterval = 1
  ),
  randomLandscapes = list(.plotInitialTime = NA, nx = 20, ny = 20))

modules <- list("randomLandscapes", "caribouMovement")
paths <- list(
  modulePath = system.file("sampleModules", package = "SpaDES.core"),
  outputPath = outputPath
)
opts <- options("spades.moduleCodeChecks" = FALSE,
                "spades.useRequire" = FALSE) # not necessary for example
mySim <- simInitAndSpades(times = times, params = parameters, modules = modules,
                          paths = paths)

## try with list()
parameters <- list(
  .globals = list(stackName = "landscape"),
  caribouMovement = list(
    .saveObjects = list("caribou", "habitatQuality"),
    .saveInitialTime = 1, .saveInterval = 1
  ),
  randomLandscapes = list(.plotInitialTime = NA, nx = 20, ny = 20))

mySim <- simInitAndSpades(times = times, params = parameters, modules = modules,
                 paths = paths)

list.files(paths$outputPath)
```

**Comment by CeresBarros** [comment]
@mbelkebrea, try installing `CeresBarros/SpaDES.core@issue241_saveFilesBug` and see if that helps while we wait for others to review the [PR](https://github.com/PredictiveEcology/SpaDES.core/pull/242)

**Comment by eliotmcintire** [comment]
Pulled in the [PR](https://github.com/PredictiveEcology/SpaDES.core/pull/242)
