### ISSUE TITLE
Use `ggplotify` in Plots to plot non-ggplot graphics 

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#243]
I've often had trouble using `Plots` to plot `base` and `lattice` graphics, because it either expects a `ggplot` object or because (for a variety of reasons) `Plot` won't support the said plot object.

I just became aware of the `ggplotify` package which is able to convert several types of graphics objects into `ggplot` and wonder if we could use it internally to expand `Plots` to other types of objects - meaning that the user won't have to lose time finding ways to convert their plot objects.

I haven't thought of _how_ exactly this would be implemented and was more hoping to gauge if others think there is value in this.

Here's an example of how I'm using `Plots` and `ggplotify` at the moment.
```
if(!require("Require")) {
  remotes::install_github("PredictiveEcology/Require")
}
Require(c("lattice", "ggplotify", "PredictiveEcology/SpaDES.core"))

p1 <- densityplot(~mpg|cyl, data=mtcars)
Plots(data = p1, fn = as.ggplot, filename = plotFile,
      ggsaveArgs = list(width = 5, height = 4, dpi = 300, bg = "white", units = "in"),
      types = c("screen", "png"), .plotInitialTime = 1)

```

**Comment by eliotmcintire** [comment]
This works now, thanks to PR #246
