### ISSUE TITLE
use consistent per-module paths for output figures

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#248]
> Can you also ensure file names are prefixed by the module name? 

I partially agree with this. One the one hand, yes, appending the module name would facilitate finding figures and even interpreting them. However,
1. it feels strange to me to do this for one module only
2. If we propagate across modules that will mean changing many figure names
3. in some cases, we may end up with very long filenames.

I wonder if, instead, we could (in this and and other modules in which to do this) create a module parameter that governs where figures are saved (e.g. `P(sim)$.plotsPath`). By default, `Plots` saves to a `file.path(outputPath(sim), "figures")` folder. This could still be the default `P(sim)$.plotsPath`, but the user could change that to  `file.path(outputPath(sim), "figures", "<moduleName>")`. 

This partly addresses my point no. 1, in that the figure names would remain the same. It doesn't address no 2, as it still means changing internal code of several modules (and creating a new parameter), if we want to propagate this across modules. It fully addresses no 3, as filenames would remain as short/long as they currently are

_Originally posted by @CeresBarros in https://github.com/PredictiveEcology/Biomass_speciesParameters/issues/32#issuecomment-1670491545_

----

Defining this in `SpaDES.core` and providing an accessor should be straightforward.

**Comment by CeresBarros** [comment]
yes
