### ISSUE TITLE
allow json/yaml for metadata in addition to native R

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#25]
_From @achubaty on March 31, 2015 23:11_

- standardized & better integration with other systems
- lower overhead

_Copied from original issue: PredictiveEcology/SpaDES#144_

**Comment by achubaty** [comment]
_From @gnewton on April 1, 2015 1:39_

Which does R better support?
Looking at this stackoverflow (from 2014) suggest json might be a better choice?
    http://stackoverflow.com/questions/6364805/making-a-complex-yaml-from-r

However, this suggest yaml is OK: http://www.inside-r.org/packages/cran/yaml

Perhaps do some tests with your use cases to verify there are no issues with this yaml package...

**Comment by achubaty** [comment]
related: #172, #175, #176, #182

**Comment by eliotmcintire** [comment]
Closing -- low priority. Tagging "Not Done"
