### ISSUE TITLE
Either documentation or default is wrong: `newModule()`

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/SpaDES.core#273]
Documentation of newModule says:

> `path`     Character string. Subdirectory in which to place the new module code file. The default is the current working directory.

However, when creating a new module the default path is actually the cache path
```
> getwd()
[1] "C:/Users/Tati/Documents/GitHub/EFI_webinar"
> SpaDES.core::newModule("testModule")
New module testModule created at C:/Users/Tati/Documents/GitHub/NWT/cache/tmp/RtmpqWw5f7/SpaDES/modules
(...)
> SpaDES.core::getPaths()
$cachePath
[1] "C:/Users/Tati/Documents/GitHub/NWT/cache/tmp\\RtmpqWw5f7/reproducible/cache"
(...)
```

In my opinion, the documentation expresses the correct behavior, and the module should be created in the current working directory, except if this would break any further functionalities (which I don't believe, but who knows)

**Comment by achubaty** [comment]
thanks for spotting this. it's using `getOption("spades.modulePath")` as the default, which is initialized to a random temp directory.

**Comment by eliotmcintire** [comment]
I remember this conversation a while ago. I agree with @tati-micheletti . The default should not be random, but current directory. When it is random, the user can easily, accidentally, lose their work without realizing it.
