### ISSUE TITLE
revdep check failures (similar to CRAN)

### ISSUE THREAD

**Issue by rsbivand** [PredictiveEcology/SpaDES.core#275]
With R 4.4.0, GDAL 3.9.0 beta1, Fedora 40, packages fully updated: 

[00check.log](https://github.com/PredictiveEcology/SpaDES.core/files/15106670/00check.log)

[test-all.Rout.zip](https://github.com/PredictiveEcology/SpaDES.core/files/15106669/test-all.Rout.zip)

similar to:

https://www.stats.ox.ac.uk/pub/bdr/noSuggests/SpaDES.core.out

**Comment by achubaty** [comment]
Thanks. The original test previously failed on R-devel (4.5; 2024-04-10 r86396) but not 4.4 alpha or earlier. Now it's failing in the 4.4.0 release, so I'll update and resubmit to CRAN.

Note those CRAN checks are stale, from a very old version of the package.

**Comment by achubaty** [comment]
v2.0.5 just accepted by CRAN
