### ISSUE TITLE
stricter checking of module compatibility

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#28]
_From @achubaty on March 31, 2015 23:0_

check for and message the user re: the following
- [ ] checking extents of maps
- [ ] checking the validity timeframe of modules
- [ ] deeper object name/class checking, especially global params

Most of this will need to be done on a per-module basis, with decisions being made by the module developer, but it could be useful to bake in some of this functionality

_Copied from original issue: PredictiveEcology/SpaDES#142_

**Comment by eliotmcintire** [comment]
Closing. Low priority. Labelled, "NotDone"
