### ISSUE TITLE
add tests for downloadData(..., overwrite = TRUE)

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#35]
from https://github.com/PredictiveEcology/SpaDES.core/pull/34, assigned to @CeresBarros

**Comment by achubaty** [comment]
also, please address this note from R CMD check:

```r
* checking R code for possible problems ... NOTE
downloadModule,character-missing-missing-missing-missing-missing-ANY-ANY:
  no visible binding for global variable ‘overwrite’
Undefined global functions or variables:
  overwrite
```

**Comment by CeresBarros** [comment]
K!

**Comment by CeresBarros** [comment]
Solved: 1b6da4ab32f7d41c46d13ce80db805732d51f833

**Comment by achubaty** [comment]
I don't see where the tests were added...

**Comment by CeresBarros** [comment]
I’m working on the tests, still, but Eliot has added the variable definition mentioned in the issue.
