### ISSUE TITLE
fix CRAN check results

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#36]
https://cran.r-project.org/web/checks/check_results_SpaDES.core.html

A few warnings and one error with latest version (0.1.1) need to be addressed ASAP.

**Comment by eliotmcintire** [comment]
What does it mean when the user's folders are Read Only?
```
Warning in gzfile(file, mode) :
  cannot open compressed file ‘/home/hornik/tmp/R.check/r-release-gcc/Work/build/Packages/.snapshot.RDS’, probable reason ‘Read-only file system’
```

**Comment by achubaty** [comment]
Not sure why.

**Comment by achubaty** [comment]
Some of this appear to be spurious (like not finding `tidyr`).

**Comment by mattdowle** [comment]
Hi,
Thanks for merging https://github.com/PredictiveEcology/SpaDES.core/pull/64
We're tracking CRAN status of packages using data.table in this issue : https://github.com/Rdatatable/data.table/issues/2915.  Please see the top of that issue for why the CRAN error status affects us upstream.
Do you have an ETA for updating SpaDES.core and SpaDES.tools on CRAN?
Best, Matt

**Comment by achubaty** [comment]
@mattdowle CRAN has given us until June 10 to fix, and we are working to resolve these and various other problems in dependencies too.

**Comment by mattdowle** [comment]
Great thank you!  The updates on CRAN pass fine now.  Think you can close this issue.
