### ISSUE TITLE
ensure downloadModule works on private repos

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#37]
We use the `GITHUB_PAT` for downloads and make note of it in the `downloadModule` documentation:
https://github.com/PredictiveEcology/SpaDES.core/blob/master/R/module-repository.R#L245-247

BUT the (recently added) previous paragraph says that only public repos work.
https://github.com/PredictiveEcology/SpaDES.core/blob/master/R/module-repository.R#L242-243

- [x] improve documentation to explain how to set up the PAT and use it locally

**Comment by eliotmcintire** [comment]
Apparently not recently added:
7cc310cc208c3b04a8f70cd17b0ec7555ba2da2e
 June 30, 2017 --> which predates the existence of `SpaDES.core`

**Comment by achubaty** [comment]
Aha! You're right.

**Comment by achubaty** [comment]
Probably the easiest way to test this is to copy the test module from the SpaDES-modules repo and copy it to a new private repo.

Incidentally, do we have a helper function to create the necessary dir structure for new module repos?
