### ISSUE TITLE
current R CMD check failures: argument "what" is missing, with no default

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#41]
Not sure what suddenly triggered these but there appears to be an issue with caching. The same error is causing failures in vignette building:

```r
 argument "what" is missing, with no default
```

-----

```r
checking tests ... ERROR
  Running ‘test-all.R’ [86s/90s]
Running the tests in ‘tests/test-all.R’ failed.
Last 13 lines of output:
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 63 SKIPPED: 33 FAILED: 36
  1. Error: test cache (@test-cache.R#14) 
  2. Error: test event-level cache (@test-cache.R#69) 
  3. Error: test module-level cache (@test-cache.R#125) 
  4. Error: test .prepareOutput (@test-cache.R#201) 
  5. Error: test .robustDigest for simLists (@test-cache.R#259) 
  6. Error: test checkpointing (@test-checkpoint.R#26) 
  7. Error: test checkpointing with disk-backed raster (@test-checkpoint.R#73) 
  8. Error: /Users/travis/build/PredictiveEcology/SpaDES.core/SpaDES.core.Rcheck/00_pkg_src/SpaDES.core/man/moduleMetadata.Rd 
  9. Error: /Users/travis/build/PredictiveEcology/SpaDES.core/SpaDES.core.Rcheck/00_pkg_src/SpaDES.core/man/moduleVersion.Rd 
  1. ...
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by eliotmcintire** [comment]
This was an old issue. `inherits` doesn't work on `simList`. It was LONG ago changed to class(   ). I am undoing the portion of the commit that made this 0129288093e88cc1e47c88b30b362b35d62d67e6 . It must stay `class` or we need to diagnose why `inherits` fails and fix that. For now, `class` is fine.

**Comment by eliotmcintire** [comment]
It may have been a speed issue, but I think both are "fast enough"

```
microbenchmark::microbenchmark(inherits(sim, "simList"), class(sim)== "simList", is(sim, "simList"), times = 1e4)
Unit: nanoseconds
                     expr  min   lq      mean median   uq   max neval cld
 inherits(sim, "simList")  880 1174 1778.6009   1467 1760 23462 10000  b 
  class(sim) == "simList"  293  587  967.7314    880  880 43698 10000 a  
       is(sim, "simList") 4986 6159 7612.0034   6452 6746 50443 10000   c
```

**Comment by achubaty** [comment]
I've fixed it in my branch.

Note we use `inherits(sim, "simList")` elsewhere with no issue.

**Comment by achubaty** [comment]
if it's a speed issue, should we change all instances of `inherits(sim, "simList")` to `class(sim) == "simList"`?

**Comment by eliotmcintire** [comment]
I think the difference is only relevant if the function is being run EVERY event. Even then, probably fine. I believe inherits(...) is "more correct", but I don't really know the strong arguments.

**Comment by eliotmcintire** [comment]
See discussion here: https://stackoverflow.com/questions/27923345/whats-the-difference-between-is-and-inherits 
(is vs. inherits). They note the integer difference ... I will look for discussions about class vs inherits

**Comment by achubaty** [comment]
Yes, I believe `inherits` is more correct.

But since it's in the `doEvent`, I'll make the change based on speed.
