### ISSUE TITLE
document use of Rmd file for data description

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#42]
Allow module developer to optianally use `moduleName/moduleName_data.Rmd` file to document data.

Using this feature in `SpaDES.shiny` (https://github.com/PredictiveEcology/SpaDES.shiny/commit/7fb05ae960cbcba7fbf37fa7497f1fb95944ee0b).

**Comment by eliotmcintire** [comment]
Closing -- low priority -- adding label "Not Done"
