### ISSUE TITLE
create dev documentation for message colour usage

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#43]
I'd like to ensure `crayon` colours for messages are used consistently (*e.g.*, consistent colours for different types of messages). Should be documented in the wiki dev docs.

**Comment by achubaty** [comment]
extend this to also include other message formatting guidlines

**Comment by achubaty** [comment]
@eliotmcintire started this in https://github.com/PredictiveEcology/reproducible/pull/155/commits/ed6682ba1cc789fa2459e84a2b7fccdc29be3a0e

- `blue` for all `Cache` functions;
- `cyan` for all `prepInputs` functions

**Comment by eliotmcintire** [comment]
No documentation happened, but efforts have been made to make this happen. Closing.
