### ISSUE TITLE
Attach name to depends(sim)@dependencies

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/SpaDES.core#44]
Currently, `depends(sim)@dependencies` is an unnamed list if there is >1 module and a named list if there is 1 module, and it actually is missing a level. This should:

1. Always be a 2 level, nested list (moduleName --> dependencies) even when only 1 module
2. Add a name attribute (module name) that that list. Currently it is unnamed.

**Comment by achubaty** [comment]
done in 44cdd43616ab0b8c22ed2fe2351a59415e4ac310. can this be closed?
