### ISSUE TITLE
improve module code checks

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/SpaDES.core#52]
#### misses local variables passed as character and evaluated later and variables inside loops

Not really a big deal, just something I noted. Whenever I am using `eval(parse(text = "variable")))`, `simInit()` doesn't recognize the variable as such and throws a warning during module checking. Not such a big deal, but you might want to fix it at some point. 

The checking is also suggesting some of my created lists are not being used, but it is not recognizing I am actually using them inside a loop.

#### incorrectly identifies named lists as objects

Module code checking identifies named lists as objects when defaults are created in .inputObjects:

```r
inputObjects = bind_rows(  
    expectsInput(objectName = "birdList", objectClass = "list",  
                  desc = "Example of a list of bird species containing random values")  
)  

.inputObjects <- function(sim) {
  if (!suppliedElsewhere("birdList", sim)){
  sim$birdList <- list()
  sim$birdList[["BBWA"]] <- runif(n = 10, min = 5, max = 10)
}
```

This also happens in the events. In the same way, it does not recognize a named list created in the module:

```r
outputObjects = bind_rows(
    createsOutput(objectName = "predictRas", objectClass = "list", 
                  desc = "List of years, which is a list of species with density rasters")
  )
doEvent.predictBirds = function(sim, eventTime, eventType) {
  switch(
    eventType,
    init = {
      sim$predictRas[[paste0("Year", time(sim))]] <- functionX()
      # schedule future event(s)
      sim <- scheduleEvent(sim, time(sim), "predictBirds", "predictBirdsDensities")
    }, (...)
```

After running simInit:

```r
###### Module Code Checking - Still experimental - please report problems ######## 
C:/Users/tmichele/GitHub/borealBirdsAndForestry/modules/predictBirds/predictBirds.R
predictBirds: inputObjects: BBWA is assigned to sim inside .inputObjects, but is not declared in inputObjects
predictBirds: module code: predictRas is declared in outputObjects, but is not assigned in the module
```

[ UPDATE ] 

Temporary variables used inside the `lapply` function (i.e. variable `x` in `lapply(X = 1:3, FUN = function(x){ }))` are also pointed out as objects that are not declared in inputObjects.

```r
###### Module Code Checking - Still experimental - please report problems ######## 
C:/Users/tmichele/GitHub/borealBirdsAndForestry/modules/birdDensityTrends/birdDensityTrends.R
birdDensityTrends: inputObjects: nSp, nRas are used from sim inside .inputObjects, but are not declared in inputObjects
```

**Comment by eliotmcintire** [comment]
Closing -- low priority -- Labelling "NotDone"
