### ISSUE TITLE
suppliedElsewhere documentation needs to be clarified

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#65]
for the argument `object` we read:
"Character vector or sim object in the form sim$objName"

To me, this suggests that 
```
mySim <- simInit()
mySim$test <- 1
suppliedElsewhere("test", mySim) 
```
and
```
suppliedElsewhere(mySim$test, mySim) 
## or perhaps
suppliedElsewhere(sim$test, mySim) 
```
should all be `TRUE`. But this is not the case. This also `FALSE`:
`suppliedElsewhere("mySim$test", sim = mySim)`

Bottow line, the documentation needs to be clarified here.

**Comment by achubaty** [comment]
done in 2615082c
