### ISSUE TITLE
scheduleEvent doesn't like integer eventTime(s)?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#70]
When scheduling events in a module, I noticed that scheduling was happening a year after it should when I used integer (?) variables. I think the being "integer"is the issue here, since scheduling during init was correct when using numeric variables (e.g. .plotInitialTime).
In other "words":

```r
## let's assume time(sim) = 2
year <- 4L
scheduleEvent(blah, eventTime = year, blah) ## schedules to year 5
year <- time(sim) + 2
scheduleEvent(blah, eventTime = year, blah) ## schedules to year 4
```

**Comment by achubaty** [comment]
can you try rerunning with `year <- 4.0` to if it is ant integer problem?

**Comment by CeresBarros** [comment]
Interestingly doing `year <- 4.0` produced the same result as `year <- 4L`

**Comment by achubaty** [comment]
it may be an issue with the way units are done. if you do something like `start(sim) + 4L` it works because the units are automatically dealt with, whereas a numeric doesn't have the extra attribute.

@eliotmcintire or I will have to take a closer look.

**Comment by achubaty** [comment]
it's likely an easy fix. a stupid workaround would be:

```r
year <- start(sim) - start(sim) + 4L
```

**Comment by achubaty** [comment]
@CeresBarros was this still an issue?

**Comment by eliotmcintire** [comment]
can't reproduce. But have written a test that tests for this, and it appears fine.  See 2c52cf0809b3a98659920c3e4b464b75252406c5
