### ISSUE TITLE
improve use of globals

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#73]
ensure `.globals` list gets added to simList class (https://github.com/PredictiveEcology/SpaDES.core/blob/master/R/simList-class.R#L106) and use any global parameter values supplied to override parameter values in modules. this makes it easier to use a single value for all params with same name in multiple modules.

**Comment by eliotmcintire** [comment]
I don't know how to implement this. It has be 2 years. Closing -- low priority.
