### ISSUE TITLE
implement 'useCI' or similar to set up basic .travis file for automated module testing

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#74]
see [here](https://stackoverflow.com/questions/35322647/how-do-i-set-up-travis-for-non-package-code) for getting travis setup for non-R packge code.

We would need to:

1. install any system dependencies (GDAL, mapshaper, etc.);  [to be done by the user]
2. install all dependency packages (start with `SpaDES` and `testthat`, then parse the module metadata for `reqdPkgs` and install them);
3. ensure the template test `.R` files each load any packages required of them and clean up after themselves.

**Comment by eliotmcintire** [comment]
@achubaty Is this done?

**Comment by achubaty** [comment]
No. automating this will be too tricky and it depends on the user setting up travis and GHA, etc. and dealing with system dependencies. (made easier using the mechanisms in place for GHA).

Since I'm doing this for several modules already, I should put this info in vignette instead so the user knows how to do it.l

**Comment by achubaty** [comment]
@eliotmcintire Apparently it's partially implemented in b42eeef3051e22239be6b7a8a9da070a6ba6fc66.

Reviewing now. Did you end up removing `usethis` from Suggests, because I am using it for this.
