### ISSUE TITLE
`.runModuleInputObjects` replaces `objects` that were changed in `.inputObjects`

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#76]
Perhaps this behaviour is intended, but I have noticed that objects that are supplied to `simInit` (via `objects = list(....)`) cannot be changed during the `simInit` call (e.g. in `.inputObjects`), as they revert to their "original" form (i.e. what was originally supplied from `.GlobalEnv`).
This is because the list of objects is not updated between `.runModuleInputObjects` calls as `simInit` loops through the list of modules.
I wonder if it wouldn't be good to actually update the list of objects from `sim` after each run of `.runModuleInputObjects`. I am thinking of a case where the input object might be e.g. a dataframe that has some information, but needs to be "completed" during the `.inputObjects ` call of a particular module before being used by another one.

here's what I propose:
9eb6504e85fc389d50734584882636e73846d41f

**Comment by CeresBarros** [comment]
I also noted that in `suppliedElsewhere` documentation it can be read: "user supplied values come *after* the module's .inputObjects" with regards to objects supplied via `simInit`. Given what I said in my comment above, I don't think this is entirely correct as `.runModuleInputObjects` makes use of user-supplied values at the time when `.runModuleInputObjects` is run.

**Comment by eliotmcintire** [comment]
These are the intended behaviors. User trumps.
