### ISSUE TITLE
check that user doesn't nuke module namespace

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#80]
add a check in user's code that checks for assignment into an object with same name as module:

```r
## yieldTables.R

Init <- function(sim) {
  sim$yieldTables <- anything ## this breaks all the things!
  return(invisible(sim))
}
```

**Comment by eliotmcintire** [comment]
This should be checked already. Is this something that was affected by recent changes to order of parsing during simInit @achubaty?

**Comment by achubaty** [comment]
I suppose it's possible. Another culprit is that Mario and Steve are using old module format.

**Comment by eliotmcintire** [comment]
Also check lockBinding in recent R 3.5x for changed behavior.

**Comment by achubaty** [comment]
The binding is being locked during parsing (towards the end of `.parsemodule`). I had only changed when `.inputObjects` was run, not when it was parsed (see c0332304286ab6ca67af82c60d5f178d6d58d8ce). Previously, `.inputObjects` was run during parsing, but before the binding was locked. Now it's being run after the parsing (*i.e.*, after the binding is locked).

**Comment by achubaty** [comment]
i think this can be closed...
