### ISSUE TITLE
is there a clean way to enable saving of all Plots to png?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#89]
rather than relying on module developers to include this functionality, it would be nice to be able to easily save plots created during simulations.

**Comment by eliotmcintire** [comment]
Do we want 1 plot per .png, or whatever is shown on the device?

**Comment by eliotmcintire** [comment]
I think there are 3 options:
1. Objects that are plots (e.g. from ggplot) could be saved on a schedule
2. Objects that can be plotted directly without massive customization (e.g. plot(sim$rasWhtyever)
3. Capture the device which may have many plots on it.

Which one(s) are most interesting?

**Comment by achubaty** [comment]
can we revisit this? open for discussion.

**Comment by eliotmcintire** [comment]
I think short answer is "No". Different mechanisms for ggplot and base plots. Closing. Labelling "Not Done"
