### ISSUE TITLE
parameter classes can't be vectors

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/SpaDES.core#91]
```
defineParameter(".useParallel", class = c("logical", "numeric),
                    default = getOption("pemisc::useParallel", FALSE), min = NA, max = NA,
                    desc = "")
```
produced 
```
Error in .parseModule(sim, as.list(modules), userSuppliedObjNames = sim$.userSuppliedObjNames,  : 
  Error in class1Def@contains[[class2]] : no such index at level 1
```

**Comment by achubaty** [comment]
I'm not sure this is a problem. Any parameter/argument really should only be a single type. I know it's convenient in this case to allow `TRUE`/`FALSE` but really this parameter should be numeric. The equivalent for `TRUE` might be `getOption("Ncpus", parallel::detectCores())`.

**Comment by achubaty** [comment]
I'll leave this open for now so @eliotmcintire and I can discuss. We might need to make corresponding changes elsewhere.

**Comment by eliotmcintire** [comment]
I am ok with vectors of classes ... numeric and logical are so commonly
interchangeable, R even accepts numerics as logicals. So, I think
SpaDES.core should accept a vector for this. Also, parsing should also
verify the class ... and show a warning if not correct. But that is for
another issue...

**Comment by eliotmcintire** [comment]
Closing. Low priority. Labelled "NotDone"
