### ISSUE TITLE
.useCache parameter documentation

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.core#93]
I'm not sure whether this is the right repo to post this issue, but it felt better than `reproducible`. 
I think a better explanation of the .useCache (module) parameter is needed (somewhere...). Latest SpaDES setups have been using this module-specific parameter to control caching at the "event" level (e.g. ` .useCache = c("init", ".inputObjects")). However I could not find documentation for this functionality anywhere, and module metadata still describes this parameter as `logical`.

**Comment by eliotmcintire** [comment]
Cache vignette in SpaDES package, I think.

**Comment by CeresBarros** [comment]
That vignette seems to only refer to .robustDigest…

**Comment by eliotmcintire** [comment]
http://spades-core.predictiveecology.org/articles/iii-cache.html

It is in the Cache vignette.

**Comment by CeresBarros** [comment]
Thanks. Could we make this more visible/accessible via R help? Maybe it could be referred to in `?spades`?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by eliotmcintire** [comment]
I think that could be a good idea... Make `?spades` be a central place with
hyperlinks to many things.

**Comment by eliotmcintire** [comment]
Close with 4b5a6bdc3ea22c330b4544fba8b5230981fc34b7
